version: "3.8"

services:
  memcached:
    image: memcached:latest
    restart: unless-stopped
    container_name: weather-app-memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64
    networks:
      - backend

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  localstack:
      image: localstack/localstack:latest
      container_name: localstack
      env_file:
        - .env
      environment:
        - LOCALSTACK_SERVICES=s3
        - DEBUG=1
        - AWS_DEFAULT_REGION=us-east-1
      ports:
        - "4566:4566"
        - "4572:4572"
      volumes:
        - "./localstack-init-scripts:/etc/localstack/init/ready.d"
      networks:
        - backend

  api:
    container_name: weather-api
    restart: unless-stopped
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
    image: weather-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000" ]
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - backend

networks:
  backend:
    driver: bridge